output "alb_dns_name" {
  description = "El DNS público del Application Load Balancer."
  value       = aws_lb.main.dns_name
}

output "rds_endpoint" {
  description = "El endpoint de la base de datos RDS."
  value       = aws_db_instance.main.endpoint
}

output "ecr_repository_url" {
  description = "La URL del repositorio ECR para subir imágenes Docker."
  value       = aws_ecr_repository.main.repository_url
}

output "ec2_public_ip" {
  description = "IP pública de la instancia EC2 (para SSH)."
  value       = aws_instance.front.public_ip
}


output "ec2_public_ip" {
  description = "IP pública de la instancia EC2 (para SSH)."
  value       = aws_instance.back.public_ip
}


output "ec2_private_key_pem" {
  description = "Private key PEM generated by Terraform (only set if Terraform created the key pair)."
  value       = length(tls_private_key.generated) > 0 ? tls_private_key.generated[0].private_key_pem : ""
  sensitive   = true
}